export type AppTheme = string;

export interface AppConfig {
  id: string;
  key: string;
  primaryColor: string;
  accentColor: string;
  fontFamily: string;
  buttonText: string;
  orientation: string;
  leadValueEstimate: number;
  background: string;
  text: string;
  name: string;
  tagline: string;
  icon: string;
  promptRole: string;
  category: 'Legal & Finance' | 'Health & Wellness' | 'Home & Trades' | 'Tech & Lifestyle';
  affiliateLink: string;
  affiliateName: string;
  toolName: string;
  toolType: string;
  quickPrompts: string[];
  features: string[];
}

export const AppEmpireConfig: Record<string, AppConfig> = {
  'general': {
    id: '01',
    key: 'general',
    primaryColor: '#4338CA',
    accentColor: '#818CF8',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'LAUNCH TASK ASSISTANT',
    orientation: 'portrait',
    leadValueEstimate: 120,
    background: '#020617',
    text: '#FFFFFF',
    name: 'OmniAssist - General AI & Productivity',
    tagline: 'All-in-one general intelligence assistant for multi-task writing, reasoning, planning, and problem-solving.',
    icon: '🌐',
    promptRole: 'Executive AI Productivity Strategist and General Intelligence Assistant',
    category: 'Tech & Lifestyle',
    affiliateLink: 'https://workspace.google.com/?affiliate=dons-empire',
    affiliateName: 'Google Workspace Pro',
    toolName: 'Task Breakdown & Smart Productivity Planner',
    toolType: 'general_calc',
    quickPrompts: [
      'Break down a complex software launch into a 14-day prioritized milestone roadmap',
      'Draft an executive summary and project brief for a new multi-platform initiative',
      'Analyze and optimize my daily schedule for deep-work focus and maximum efficiency',
      'Synthesize key findings and action items from this problem description'
    ],
    features: ['Multi-Topic Reasoning', 'Smart Task Breakdown', 'Daily Time Blocking', 'Executive Action Roadmaps']
  },
  'medical': {
    id: '02',
    key: 'medical',
    primaryColor: '#059669',
    accentColor: '#34D399',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'BOOK MEDICAL REVIEW',
    orientation: 'portrait',
    leadValueEstimate: 150,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Clinical Health & Triage',
    tagline: 'Evidence-grounded medical wellness, symptom assessment, and clinical research.',
    icon: '⚕️',
    promptRole: 'Clinical Health Consultant and Medical Researcher',
    category: 'Health & Wellness',
    affiliateLink: 'https://www.healthiq.com/?affiliate=dons-empire',
    affiliateName: 'Health IQ Clinical',
    toolName: 'Symptom & Drug Interaction Screener',
    toolType: 'medical_calc',
    quickPrompts: [
      'Check potential interactions between Lisinopril, Metformin, and Ibuprofen',
      'Explain normal vs elevated blood pressure ranges and lifestyle remedies',
      'What are evidence-backed protocols for reducing LDL cholesterol?',
      'Interpret common blood panel markers (CBC, Lipid, Metabolic)'
    ],
    features: ['Drug Interaction Checker', 'Clinical Research Grounding', 'Blood Marker Interpreter', 'HIPAA Consent Log']
  },
  'medical_care': {
    id: '03',
    key: 'medical_care',
    primaryColor: '#0284C7',
    accentColor: '#38BDF8',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'EMERGENCY PROTOCOL CHECK',
    orientation: 'portrait',
    leadValueEstimate: 200,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Emergency Care & Clinical Diagnostics',
    tagline: 'Emergency triage protocols, vital sign diagnostic analyzer, dosage benchmarks, and patient care guidance.',
    icon: '🩺',
    promptRole: 'Board-Certified Emergency Medicine Physician and Clinical Diagnostics Specialist',
    category: 'Health & Wellness',
    affiliateLink: 'https://www.redcross.org/?affiliate=dons-empire',
    affiliateName: 'Emergency First Aid Network',
    toolName: 'Clinical Diagnostic & Emergency Care Protocol',
    toolType: 'medcare_calc',
    quickPrompts: [
      'Assess Emergency Severity Index (ESI) for acute chest tightness with shortness of breath',
      'Calculate weight-based pediatric acetaminophen and ibuprofen safe dosage benchmarks',
      'Immediate first-responder actions for suspected acute stroke (BE-FAST protocol)',
      'Clinical triage algorithm for suspected anaphylactic allergic reactions'
    ],
    features: ['Emergency Care Protocols', 'Vital Signs Diagnostic Index', 'Pediatric Dosage Helper', 'Acuity Scoring Matrix']
  },
  'nonprofit': {
    id: '04',
    key: 'nonprofit',
    primaryColor: '#D97706',
    accentColor: '#FBBF24',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'EVALUATE GRANT & 501(c)(3)',
    orientation: 'portrait',
    leadValueEstimate: 220,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Non-Profit Impact & Grant Navigator',
    tagline: '501(c)(3) statutory compliance, grant proposal drafting, donor impact modeling, and fundraising ROI estimation.',
    icon: '🤝',
    promptRole: 'Senior Non-Profit Executive Director and Grant Writing Strategist',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.guidestar.org/?affiliate=dons-empire',
    affiliateName: 'GuideStar Charity Pro',
    toolName: 'Non-Profit Grant & Fundraising Impact Calculator',
    toolType: 'nonprofit_calc',
    quickPrompts: [
      'Draft a persuasive Statement of Need for a $75,000 community youth education grant',
      'What are the IRS Form 990 public support test requirements for 501(c)(3) status?',
      'Calculate fundraising event ROI and donor acquisition cost for an annual gala',
      'Structure a multi-year major donor stewardship and pledge retention strategy'
    ],
    features: ['501(c)(3) Compliance Checker', 'Grant Proposal Generator', 'Fundraising Event ROI Model', 'Donor Retention & Impact Forecast']
  },
  'law': {
    id: '05',
    key: 'law',
    primaryColor: '#1E3A8A',
    accentColor: '#F59E0B',
    fontFamily: '"Playfair Display", serif',
    buttonText: 'CONSULT LEGAL SPECIALIST',
    orientation: 'portrait',
    leadValueEstimate: 350,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Legal Services & Contracts',
    tagline: 'Statute-grounded contract analysis, NDA drafting, and compliance review.',
    icon: '⚖️',
    promptRole: 'Senior Legal Advisor and Contract Specialist',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.legalzoom.com/?affiliate=dons-empire',
    affiliateName: 'LegalZoom Pro',
    toolName: 'Contract Clause & Risk Auditor',
    toolType: 'legal_calc',
    quickPrompts: [
      'Draft a standard Non-Disclosure Agreement (NDA) for software development',
      'Analyze the risks in a non-compete clause for independent contractors',
      'What are the key liability disclaimers needed for an online SaaS platform?',
      'Explain the difference between LLC and S-Corp tax liability'
    ],
    features: ['NDA & Contract Generator', 'Statute Grounding', 'Risk & Liability Score', 'Precedent Lookup']
  },
  'personal_injury': {
    id: '06',
    key: 'personal_injury',
    primaryColor: '#991B1B',
    accentColor: '#F87171',
    fontFamily: '"Playfair Display", serif',
    buttonText: 'EVALUATE MY CLAIM',
    orientation: 'portrait',
    leadValueEstimate: 850,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Personal Injury & Litigation Claims',
    tagline: 'Accident claim damage valuation, settlement multipliers, and loss estimation.',
    icon: '🏛️',
    promptRole: 'Personal Injury Claim Evaluator and Legal Damages Analyst',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.nolo.com/?affiliate=dons-empire',
    affiliateName: 'Nolo Legal Claims',
    toolName: 'Settlement Value Multiplier Calculator',
    toolType: 'injury_calc',
    quickPrompts: [
      'Calculate estimated settlement value for rear-end collision with soft tissue injury',
      'What documentation is required to prove lost wages after a vehicular accident?',
      'How do insurance adjusters calculate pain and suffering multipliers (1.5x - 5x)?',
      'Draft a formal demand letter outline for an auto insurance settlement'
    ],
    features: ['Settlement Multiplier', 'Lost Wage Estimator', 'Demand Letter Drafter', 'Damage Valuation']
  },
  'real_estate': {
    id: '07',
    key: 'real_estate',
    primaryColor: '#0F766E',
    accentColor: '#F97316',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'CONNECT WITH RE AGENT',
    orientation: 'portrait',
    leadValueEstimate: 500,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Real Estate Pro & Comps',
    tagline: 'Property market comps, cap rate analysis, ROI calculations, and listing copy.',
    icon: '🏠',
    promptRole: 'Licensed Real Estate Broker and Investment Property Analyst',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.zillow.com/?affiliate=dons-empire',
    affiliateName: 'Zillow Premier',
    toolName: 'Cap Rate & Monthly Mortgage Calculator',
    toolType: 'real_estate_calc',
    quickPrompts: [
      'Calculate Cap Rate and Cash-on-Cash Return on a $450k duplex with $3,400 rent',
      'Write a high-converting luxury MLS listing description for a 4-bed suburban home',
      'What are the key tax benefits of a 1031 Exchange for rental properties?',
      'Analyze the impact of current 6.8% interest rates vs 30-year fixed amortization'
    ],
    features: ['Cap Rate & ROI Model', 'Mortgage Amortization', 'MLS Listing Copywriter', '1031 Exchange Advisor']
  },
  'finance': {
    id: '08',
    key: 'finance',
    primaryColor: '#1D4ED8',
    accentColor: '#FACC15',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'GET FINANCIAL PLAN',
    orientation: 'portrait',
    leadValueEstimate: 400,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Wealth Management & Pilot',
    tagline: 'Asset allocation modeling, compound interest wealth curves, and retirement targets.',
    icon: '📈',
    promptRole: 'Certified Financial Planner and Wealth Strategist',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.nerdwallet.com/?affiliate=dons-empire',
    affiliateName: 'NerdWallet Pro',
    toolName: 'Compound Growth & FIRE Calculator',
    toolType: 'finance_calc',
    quickPrompts: [
      'Model 30-year growth of $1,000/mo invested in S&P 500 at 8.5% annual return',
      'Explain optimal asset allocation strategy for moderate risk 40-year-old',
      'Calculate FIRE (Financial Independence) target number with $75,000 annual spend',
      'Compare Traditional vs Roth IRA contributions for $120k income bracket'
    ],
    features: ['Compound Wealth Simulator', 'FIRE Retirement Model', 'Asset Allocation Matrix', 'Tax Advantage Planner']
  },
  'tax': {
    id: '09',
    key: 'tax',
    primaryColor: '#15803D',
    accentColor: '#4ADE80',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'TAX DEFENSE CONSULT',
    orientation: 'portrait',
    leadValueEstimate: 250,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Tax Shield & Audit Defense',
    tagline: 'IRS deduction optimization, write-off auditing, and self-employment strategy.',
    icon: '📊',
    promptRole: 'Enrolled Agent and Tax Defense Strategist',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.turbotax.com/?affiliate=dons-empire',
    affiliateName: 'TurboTax Defense',
    toolName: 'Self-Employment Tax & Deduction Calculator',
    toolType: 'tax_calc',
    quickPrompts: [
      'Calculate estimated quarterly self-employment taxes on $140,000 net 1099 income',
      'What legitimate home office deductions can I take for a dedicated 200 sq ft workspace?',
      'Explain Section 179 vehicle depreciation rules for vehicles over 6,000 lbs GVWR',
      'How can an S-Corporation owner optimize salary vs shareholder distributions?'
    ],
    features: ['Quarterly Tax Estimator', 'Section 179 Vehicle Write-off', 'Home Office Deduction', 'S-Corp Distribution Audit']
  },
  'dental': {
    id: '10',
    key: 'dental',
    primaryColor: '#0891B2',
    accentColor: '#38BDF8',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'BOOK DENTAL EXAM',
    orientation: 'portrait',
    leadValueEstimate: 200,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Dental Care & Emergency Triage',
    tagline: 'Dental procedure cost estimates, symptom triage, and post-op care guidance.',
    icon: '🦷',
    promptRole: 'Dental Surgeon and Oral Health Specialist',
    category: 'Health & Wellness',
    affiliateLink: 'https://www.1800dentist.com/?affiliate=dons-empire',
    affiliateName: '1-800-DENTIST Network',
    toolName: 'Dental Procedure Cost & Emergency Triage',
    toolType: 'dental_calc',
    quickPrompts: [
      'What is the standard price range for a porcelain crown vs dental implant?',
      'Emergency steps for a chipped or knocked-out permanent tooth',
      'What causes acute tooth sensitivity to cold and when does it require a root canal?',
      'Post-extraction recovery protocol to prevent dry socket'
    ],
    features: ['Emergency Triage Matrix', 'Procedure Cost Benchmarks', 'Post-Op Care Guide', 'Insurance Coverage Estimator']
  },
  'chiropractic': {
    id: '11',
    key: 'chiropractic',
    primaryColor: '#7E22CE',
    accentColor: '#C084FC',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'SCHEDULE ADJUSTMENT',
    orientation: 'portrait',
    leadValueEstimate: 120,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Chiropractic & Spine Health',
    tagline: 'Spinal ergonomics, posture evaluation, disc decompression, and stretch routines.',
    icon: '🦴',
    promptRole: 'Doctor of Chiropractic and Ergonomics Specialist',
    category: 'Health & Wellness',
    affiliateLink: 'https://www.chirotrust.org/?affiliate=dons-empire',
    affiliateName: 'ChiroTrust Network',
    toolName: 'Ergonomic Desk & Posture Score Index',
    toolType: 'chiro_calc',
    quickPrompts: [
      'Analyze symptoms of L4-L5 lumbar disc herniation vs sciatica nerve impingement',
      'Daily 5-minute desk mobility and thoracic spine decompression routine',
      'How should a workstation monitor and chair be ergonomically configured?',
      'Non-surgical decompression and exercise options for chronic lower back stiffness'
    ],
    features: ['Posture Score Index', 'Ergonomic Desk Guide', 'Sciatica Triage', 'Spinal Stretch Protocols']
  },
  'auto_repair': {
    id: '12',
    key: 'auto_repair',
    primaryColor: '#C2410C',
    accentColor: '#FB923C',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'GET REPAIR ESTIMATE',
    orientation: 'portrait',
    leadValueEstimate: 300,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Auto Mechanic & Diagnostics',
    tagline: 'OBD-II trouble code lookup, repair quote auditing, and mechanic troubleshooting.',
    icon: '🔧',
    promptRole: 'ASE Master Certified Automotive Technician',
    category: 'Home & Trades',
    affiliateLink: 'https://www.repairpal.com/?affiliate=dons-empire',
    affiliateName: 'RepairPal Certified',
    toolName: 'OBD-II Decoder & Repair Quote Auditor',
    toolType: 'auto_calc',
    quickPrompts: [
      'Decode OBD-II code P0420 (Catalytic Converter Efficiency Below Threshold)',
      'Is $1,250 a fair price for front brake pads, rotors, and caliper replacement?',
      'Troubleshoot squealing sound when turning steering wheel at low speeds',
      'Recommended maintenance schedule for 100,000-mile engine timing belt & water pump'
    ],
    features: ['OBD-II Code Database', 'Labor Rate Benchmark', 'Part Cost Auditor', 'Maintenance Schedules']
  },
  'roofing': {
    id: '13',
    key: 'roofing',
    primaryColor: '#334155',
    accentColor: '#F59E0B',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'REQUEST ROOF INSPECTION',
    orientation: 'portrait',
    leadValueEstimate: 600,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Roofing & Exterior Contractor',
    tagline: 'Square footage pitch multiplier, hail/storm damage auditing, and material quotes.',
    icon: '🏗️',
    promptRole: 'Master Roofing Contractor and Storm Damage Estimator',
    category: 'Home & Trades',
    affiliateLink: 'https://www.homeadvisor.com/?affiliate=dons-empire',
    affiliateName: 'HomeAdvisor Pro',
    toolName: 'Roof Square Footage & Shingle Cost Estimator',
    toolType: 'roof_calc',
    quickPrompts: [
      'Calculate total roofing squares and waste factor for a 2,400 sq ft home with 6:12 pitch',
      'Compare cost and durability of Architectural Asphalt Shingles vs Standing Seam Metal',
      'How to document hail impact damage for an insurance claim adjustment?',
      'What are the warning signs of flashing failure around roof chimneys and valleys?'
    ],
    features: ['Pitch Multiplier Matrix', 'Roof Squares Calculator', 'Material Cost Comparison', 'Insurance Storm Audit']
  },
  'hvac': {
    id: '14',
    key: 'hvac',
    primaryColor: '#0369A1',
    accentColor: '#EF4444',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'HVAC SERVICE CALL',
    orientation: 'portrait',
    leadValueEstimate: 250,
    background: '#020617',
    text: '#FFFFFF',
    name: 'HVAC & Climate Master',
    tagline: 'BTU & tonnage load calculator, SEER2 energy savings, and AC troubleshooting.',
    icon: '❄️',
    promptRole: 'HVAC Engineering Specialist and Master Technician',
    category: 'Home & Trades',
    affiliateLink: 'https://www.angi.com/?affiliate=dons-empire',
    affiliateName: 'Angi Certified HVAC',
    toolName: 'Manual J BTU Load & SEER Savings Calculator',
    toolType: 'hvac_calc',
    quickPrompts: [
      'Calculate AC tonnage sizing for a 2,200 sq ft home in hot climate zone 3',
      'Estimate 10-year electricity savings upgrading from 10 SEER to 18 SEER2 heat pump',
      'Troubleshoot why central AC is running continuously but not blowing cold air',
      'Pros and cons of dual-fuel heat pump system vs traditional gas furnace'
    ],
    features: ['Manual J Tonnage Sizer', 'SEER2 Energy Savings', 'Troubleshooting Decision Tree', 'Rebate Eligibility Guide']
  },
  'it_support': {
    id: '15',
    key: 'it_support',
    primaryColor: '#166534',
    accentColor: '#22C55E',
    fontFamily: '"JetBrains Mono", monospace',
    buttonText: 'REQUEST IT SECURITY SCAN',
    orientation: 'portrait',
    leadValueEstimate: 450,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Cybersecurity & IT Defense',
    tagline: 'Port vulnerability analysis, bash/PowerShell automation, and network hardening.',
    icon: '💻',
    promptRole: 'Chief Information Security Officer and Systems Administrator',
    category: 'Tech & Lifestyle',
    affiliateLink: 'https://www.geeksquad.com/?affiliate=dons-empire',
    affiliateName: 'Geek Squad Enterprise',
    toolName: 'Subnet & Port Security Vulnerability Checker',
    toolType: 'it_calc',
    quickPrompts: [
      'Generate a hardened Linux iptables firewall script blocking common DDoS attack vectors',
      'Explain zero-trust network architecture implementation for remote workforce',
      'Audit common active ports (22, 80, 443, 3389) for security vulnerabilities',
      'Write a PowerShell script to audit stale Active Directory user accounts'
    ],
    features: ['Firewall Script Generator', 'Port Vulnerability Matrix', 'Zero-Trust Architect', 'Log Analysis Tool']
  },
  'insurance': {
    id: '16',
    key: 'insurance',
    primaryColor: '#0F766E',
    accentColor: '#14B8A6',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'GET INSURANCE QUOTE',
    orientation: 'portrait',
    leadValueEstimate: 200,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Insurance Broker Pro',
    tagline: 'Comparative policy auditing, coverage gap detection, and premium optimization.',
    icon: '🛡️',
    promptRole: 'Licensed Independent Insurance Broker',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.policygenius.com/?affiliate=dons-empire',
    affiliateName: 'Policygenius Quotes',
    toolName: 'Coverage Needs & Premium Gap Estimator',
    toolType: 'insurance_calc',
    quickPrompts: [
      'Calculate recommended Term Life Insurance coverage for 35-year-old with $110k income',
      'What is the difference between Actual Cash Value (ACV) and Replacement Cost Value (RCV)?',
      'How much umbrella insurance liability coverage is recommended for high net worth families?',
      'Ways to optimize auto insurance deductibles to save 20%+ on annual premiums'
    ],
    features: ['Life Coverage Needs Model', 'Policy Gap Detector', 'Deductible Savings Model', 'Umbrella Policy Advisor']
  },
  'home_security': {
    id: '17',
    key: 'home_security',
    primaryColor: '#1E293B',
    accentColor: '#38BDF8',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'GET SECURITY AUDIT',
    orientation: 'portrait',
    leadValueEstimate: 400,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Smart Home Security',
    tagline: 'Perimeter risk scoring, camera placement optimization, and smart IoT privacy.',
    icon: '🔒',
    promptRole: 'Physical Security Specialist and Smart Home Architect',
    category: 'Tech & Lifestyle',
    affiliateLink: 'https://www.adt.com/?affiliate=dons-empire',
    affiliateName: 'ADT Home Security',
    toolName: 'Perimeter Risk Score & Sensor Layout Builder',
    toolType: 'security_calc',
    quickPrompts: [
      'Audit perimeter vulnerabilities for a 2-story suburban single-family home',
      'Optimal camera placement angles and heights for blind-spot free driveway coverage',
      'Compare local NVR camera systems vs cloud-subscription security (PoE vs Wi-Fi)',
      'Security checklist for securing IoT smart home hub against network intrusion'
    ],
    features: ['Perimeter Vulnerability Score', 'Camera Layout Blueprint', 'PoE vs Wi-Fi Analyzer', 'IoT Hardening Checklist']
  },
  'credit_repair': {
    id: '18',
    key: 'credit_repair',
    primaryColor: '#D97706',
    accentColor: '#FDE047',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'START CREDIT REPAIR',
    orientation: 'portrait',
    leadValueEstimate: 180,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Credit Repair & Score Boost',
    tagline: 'Section 609 dispute letter generation, FICO score simulation, and debt payoff.',
    icon: '💳',
    promptRole: 'Board Certified Credit Counselor and Fair Credit Reporting Act (FCRA) Specialist',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.lexingtonlaw.com/?affiliate=dons-empire',
    affiliateName: 'Lexington Law Firm',
    toolName: 'FICO Score Simulator & Section 609 Dispute Drafter',
    toolType: 'credit_calc',
    quickPrompts: [
      'Draft a formal Section 609 FCRA dispute letter to remove inaccurate late payment from Experian',
      'How much will paying down credit card utilization from 65% to 8% boost my FICO score?',
      'Step-by-step strategy for disputing collections accounts with medical debt rules',
      'Compare Debt Avalanche vs Debt Snowball payoff timeline for $18,000 credit debt'
    ],
    features: ['Section 609 Letter Generator', 'FICO Utilization Simulator', 'FCRA Dispute Templates', 'Debt Avalanche Planner']
  },
  'fitness': {
    id: '19',
    key: 'fitness',
    primaryColor: '#EA580C',
    accentColor: '#FED7AA',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'GET WORKOUT PLAN',
    orientation: 'portrait',
    leadValueEstimate: 150,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Personal Fitness & Coach',
    tagline: 'One Rep Max (1RM) calculators, customized hypertrophy splits, and cardio plans.',
    icon: '💪',
    promptRole: 'Elite Strength & Conditioning Coach and Exercise Physiologist',
    category: 'Health & Wellness',
    affiliateLink: 'https://www.myfitnesspal.com/?affiliate=dons-empire',
    affiliateName: 'MyFitnessPal Pro',
    toolName: '1RM Strength & Hypertrophy Split Builder',
    toolType: 'fitness_calc',
    quickPrompts: [
      'Calculate One Rep Max (1RM) and percentage training loads from 225 lbs for 6 reps',
      'Design an optimal 4-day Upper/Lower hypertrophy split for intermediate lifter',
      'How to program progressive overload when strength plateaus on bench press?',
      'Zone 2 cardiovascular protocol for maximum mitochondrial density and fat oxidation'
    ],
    features: ['1RM Strength Calculator', 'Hypertrophy Split Builder', 'Zone 2 Cardio Protocols', 'Progressive Overload Tracker']
  },
  'nutrition': {
    id: '17',
    key: 'nutrition',
    primaryColor: '#65A30D',
    accentColor: '#BEF264',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'GET CUSTOM MEAL PLAN',
    orientation: 'portrait',
    leadValueEstimate: 120,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Nutrition & Diet Architect',
    tagline: 'TDEE calorie targets, macronutrient ratio breakdowns, and customized meal plans.',
    icon: '🥗',
    promptRole: 'Registered Dietitian and Sports Nutrition Specialist',
    category: 'Health & Wellness',
    affiliateLink: 'https://www.noom.com/?affiliate=dons-empire',
    affiliateName: 'Noom Personalized Plan',
    toolName: 'TDEE Calorie & Macro Target Splitter',
    toolType: 'nutrition_calc',
    quickPrompts: [
      'Calculate daily TDEE and macro targets (Protein/Carb/Fat) for 185 lb male cutting body fat',
      'Create a 7-day high-protein (180g) gluten-free meal plan on a $120/week grocery budget',
      'What are the most bioavailable micronutrient sources for iron, magnesium, and vitamin D3?',
      'Pre-workout and post-workout nutrient timing for optimal glycogen replenishment'
    ],
    features: ['TDEE & Macro Calculator', 'Custom Meal Plan Generator', 'Grocery Budget Optimizer', 'Nutrient Timing Guide']
  },
  'landscaping': {
    id: '18',
    key: 'landscaping',
    primaryColor: '#15803D',
    accentColor: '#86EFAC',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'GET LANDSCAPE QUOTE',
    orientation: 'portrait',
    leadValueEstimate: 150,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Landscaping & Outdoor Architecture',
    tagline: 'Mulch/sod/soil volume calculation, irrigation zones, and hardscape design.',
    icon: '🌳',
    promptRole: 'Landscape Architect and Master Horticulturalist',
    category: 'Home & Trades',
    affiliateLink: 'https://www.trugreen.com/?affiliate=dons-empire',
    affiliateName: 'TruGreen Pro Care',
    toolName: 'Mulch, Topsoil & Sod Volume Calculator',
    toolType: 'landscape_calc',
    quickPrompts: [
      'Calculate cubic yards of mulch needed for 850 sq ft flower beds at 3-inch depth',
      'Design a drought-tolerant xeriscape plant layout for USDA hardiness zone 8b',
      'Annual lawn fertilization and pre-emergent weed control schedule for Bermuda grass',
      'Estimate paver patio base material depth and square footage cost'
    ],
    features: ['Cubic Yard Volume Calc', 'Lawn Care Calendar', 'Xeriscape Design Guide', 'Hardscape Base Estimator']
  },
  'veterinary': {
    id: '19',
    key: 'veterinary',
    primaryColor: '#EA580C',
    accentColor: '#FDBA74',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'BOOK VET CONSULTATION',
    orientation: 'portrait',
    leadValueEstimate: 120,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Veterinary & Pet Guardian',
    tagline: 'Weight-based dosage safety, toxic food & plant screening, and pet symptom triage.',
    icon: '🐾',
    promptRole: 'Licensed Doctor of Veterinary Medicine (DVM)',
    category: 'Health & Wellness',
    affiliateLink: 'https://www.vca.com/?affiliate=dons-empire',
    affiliateName: 'VCA Animal Hospitals',
    toolName: 'Pet Weight Dosage & Toxicity Screener',
    toolType: 'vet_calc',
    quickPrompts: [
      'Emergency toxicity check: 45 lb dog ingested 2 ounces of dark chocolate 30 minutes ago',
      'Calculate Benadryl (Diphenhydramine) safe dosage by weight for a 60 lb dog',
      'What are common early signs of feline kidney disease and recommended wet food diet?',
      'Post-operative care and cone-wearing timeline after spay/neuter surgery'
    ],
    features: ['Toxicity Emergency Check', 'Weight Dosage Calculator', 'Feline & Canine Triage', 'Vaccine Schedule Guide']
  },
  'immigration': {
    id: '20',
    key: 'immigration',
    primaryColor: '#1E3A8A',
    accentColor: '#60A5FA',
    fontFamily: '"Playfair Display", serif',
    buttonText: 'CONSULT IMMIGRATION LAWYER',
    orientation: 'portrait',
    leadValueEstimate: 400,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Immigration Law & Visa Guide',
    tagline: 'Visa category eligibility screening, petition checklists, and green card timeline analysis.',
    icon: '🛂',
    promptRole: 'Senior Immigration Attorney and Visa Strategist',
    category: 'Legal & Finance',
    affiliateLink: 'https://www.boundless.com/?affiliate=dons-empire',
    affiliateName: 'Boundless Immigration',
    toolName: 'Visa Eligibility Screener & Document Checklist',
    toolType: 'immigration_calc',
    quickPrompts: [
      'Evaluate EB-2 National Interest Waiver (NIW) criteria for STEM masters degree holder',
      'What is the complete document checklist required for Form I-130 / I-485 marriage green card?',
      'Explain H-1B specialty occupation cap-exempt employer requirements (universities, non-profits)',
      'O-1 Extraordinary Ability visa evidence criteria and recommendation letter requirements'
    ],
    features: ['EB-2 NIW Screener', 'I-485 Document Checklist', 'H-1B Cap Exempt Guide', 'O-1 Evidence Matrix']
  },
  'default': {
    id: '00',
    key: 'default',
    primaryColor: '#4F46E5',
    accentColor: '#818CF8',
    fontFamily: '"Inter", sans-serif',
    buttonText: 'CONSULT AI ASSISTANT',
    orientation: 'portrait',
    leadValueEstimate: 100,
    background: '#020617',
    text: '#FFFFFF',
    name: 'Universal Empire AI',
    tagline: 'Master orchestration for all 20 specialized tools across the Don Series.',
    icon: '👑',
    promptRole: 'Universal AI Assistant and Empire Navigator',
    category: 'Tech & Lifestyle',
    affiliateLink: '#',
    affiliateName: 'Empire Global Network',
    toolName: 'Empire Multi-Node Assistant',
    toolType: 'general_calc',
    quickPrompts: [
      'Give me an overview of all 20 specialized apps in the Don Series',
      'Which app should I use to calculate my property investment returns?',
      'Help me draft a legal NDA and calculate my self-employment taxes',
      'Connect me with the Veterinary Toxicity checker for my dog'
    ],
    features: ['20-App Cross Orchestration', 'Real-time Grounding', 'Multi-Industry Intelligence', 'Export Reports']
  }
};

export const getTheme = (type: AppTheme): AppConfig => {
  return AppEmpireConfig[type] || AppEmpireConfig['default'];
};

export const ALL_EMPIRE_APPS: AppConfig[] = Object.values(AppEmpireConfig).filter(a => a.key !== 'default');
